wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    code_path: code/DeepPhospho.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1684137934.419409
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.10.9
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 1024
dataset:
  desc: null
  value: transfer_learning_1
defalut_learning_rate:
  desc: null
  value: 0.001
erls_patience:
  desc: null
  value: 25
fold_num:
  desc: null
  value: 5
gpu_num:
  desc: null
  value: '0'
model:
  desc: null
  value: efficientnet-phospho-B-15
n_epoch:
  desc: null
  value: 500
pretrain_fold_num:
  desc: null
  value: '0'
save_dir:
  desc: null
  value: /home/hb/python/efficientnet_kincnn/saved_model/0515/DeepPP_transfer_learning_1_1705_bs1024_weight0
scheduler_factor:
  desc: null
  value: 0.7
scheduler_patience:
  desc: null
  value: 7
