&id001 !!python/object/new:phospho_preprocessing.AttrDict
dictitems:
  batch_size: 1024
  dataset: transfer_learning_1
  defalut_learning_rate: 0.001
  erls_patience: 25
  fold_num: 5
  gpu_num: '0'
  model: efficientnet-phospho-B-15
  n_epoch: 500
  pretrain_fold_num: '0'
  save_dir: /home/hb/python/efficientnet_kincnn/saved_model/0515/DeepPP_transfer_learning_1_1705_bs1024_weight0
  scheduler_factor: 0.7
  scheduler_patience: 7
state: *id001
